Repository Team-Growthook/Growthook-iOS, pull requests merged in 2023-12, with the labels that each got.

#13 [Feat] #8 - 액션리스트 UI를 구현합니다
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook.xcodeproj/xcshareddata/xcschemes/Growthook.xcscheme
  Growthook/Growthook/Global/Extension/UIButton+.swift
  Growthook/Growthook/Presentation/ActionList/Cell/ActionListCompleteTableViewCell.swift
  Growthook/Growthook/Presentation/ActionList/Cell/ActionListTableViewCell.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListBottomSheetViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListReviewViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/AlertViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/CompleteViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/InprogressViewController.swift
  Growthook/Growthook/Presentation/ActionList/Model/ActionListModel.swift
  Growthook/Growthook/Presentation/ActionList/ViewController/ActionListViewController.swift
  Growthook/Growthook/Presentation/ActionList/ViewModels/ActionListViewModel.swift
  Growthook/Growthook/Presentation/ActionList/Views/ActionListSegmentedView.swift
  Growthook/Growthook/Presentation/ActionList/Views/MainTitleBarView.swift
  Growthook/Growthook/Presentation/Common/UIComponents/CustomNavigationBar.swift
  Growthook/Growthook/Presentation/Common/UIComponents/UITextViewWithTintedWhenEdited.swift
Labels: 🌱 Feat, 🐰 성우

#23 [Feat] #22 - 카카오 소셜 로그인 구현 및 뷰모델 변경
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Growthook/Growthook/Application/AppDelegate.swift
  Growthook/Growthook/Application/SceneDelegate.swift
  Growthook/Growthook/Info.plist
  Growthook/Growthook/Presentation/Home/ViewControllers/CaveListHalfModal.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
  Growthook/Growthook/Presentation/Onboarding/ViewControllers/KakaoLoginViewController.swift
Labels: 🐸 정, 🌱 Feat

#14 [ Fix] #6+ - 파일 에러를 해결하고 코드리뷰를 반영했습니다.
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Growthook/Growthook/Global/Extension/UIView+.swift
  Growthook/Growthook/Global/Extension/UIViewController+.swift
  Growthook/Growthook/Presentation/Common/UIComponents/BottomCTAButton.swift
  Growthook/Growthook/Presentation/Common/UIComponents/CustomInputView.swift
  Growthook/Growthook/Presentation/CreateCave/Model/CreateCaveModel.swift
  Growthook/Growthook/Presentation/CreateCave/View/AlertBuilder.swift
  Growthook/Growthook/Presentation/CreateCave/View/CreateCaveView.swift
  Growthook/Growthook/Presentation/CreateCave/View/EmptySeedView.swift
  Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
  Growthook/Growthook/Presentation/CreateCave/ViewController/CustomAlertViewController.swift
  Growthook/Growthook/Presentation/CreateCave/ViewController/EmptyViewController.swift
  Growthook/Growthook/Presentation/CreateCave/ViewModel/CreateCaveViewModel.swift
Labels: 🎈 Fix, 😼 민주

#26 [Feature] #25 마이페이지를 구현했습니다.
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Growthook/Growthook/Global/Literals/ImageLiterals.swift
  Growthook/Growthook/Presentation/Mypage/Controllers/MypageViewController.swift
  Growthook/Growthook/Presentation/Mypage/ViewController/MypageViewController.swift
  Growthook/Growthook/Presentation/Mypage/ViewModels/MyPageViewModel.swift
  Growthook/Growthook/Presentation/Mypage/Views/Components/MyPageListTableViewCell.swift
  Growthook/Growthook/Presentation/Mypage/Views/MyPageThookBoxView.swift
Labels: 🌱 Feat, 🦊 규보

#17 [Feat] #16 - 액션플랜 생성 뷰 상단 인사이트 조회 부분 UI를 구현했습니다.
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Growthook/Growthook/Application/SceneDelegate.swift
  Growthook/Growthook/Presentation/Common/UIComponents/CustomInputView.swift
  Growthook/Growthook/Presentation/Common/UIComponents/UITextFieldWithTinitedWhenEdited.swift
  Growthook/Growthook/Presentation/Common/UIComponents/UITextViewWithTintedWhenEdited.swift
  Growthook/Growthook/Presentation/CreateAction/Model/ActionPlanModel.swift
  Growthook/Growthook/Presentation/CreateAction/Model/InsightModel.swift
  Growthook/Growthook/Presentation/CreateAction/View/CreateActionView.swift
  Growthook/Growthook/Presentation/CreateAction/View/InsightView.swift
  Growthook/Growthook/Presentation/CreateAction/ViewController/CreateActionViewControlller.swift
  Growthook/Growthook/Presentation/CreateAction/ViewModel/CreateActionViewModel.swift
  Growthook/Growthook/Presentation/CreateCave/View/CreateCaveView.swift
  Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
  Growthook/Growthook/Presentation/CreateCave/ViewModel/CreateCaveViewModel.swift
Labels: 🦋 Design, 🌱 Feat, 😼 민주

#27 [Feat] #24 - 보관함 뷰 구현
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Global/Literals/ImageLiterals.swift
  Growthook/Growthook/Global/Literals/StringLiterals.swift
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Navigation/navi_menu_btn.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Navigation/navi_menu_btn.imageset/btn_mainmenu_ios.svg
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Navigation/navi_menu_btn.imageset/ic_delete.svg
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/close_btn.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/close_btn.imageset/Property 1=closed.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/close_btn.imageset/Property 1=closed.svg
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/close_btn.imageset/Property 1=closed@2x.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/close_btn.imageset/Property 1=closed@3x.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/open_btn.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/open_btn.imageset/Property 1=open.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/open_btn.imageset/Property 1=open.svg
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/open_btn.imageset/Property 1=open@2x.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/open_btn.imageset/Property 1=open@3x.png
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewModels/CaveDetailViewModel.swift
  Growthook/Growthook/Presentation/CaveDetail/Views/CaveDescriptionView.swift
  Growthook/Growthook/Presentation/CaveDetail/Views/CaveDetailView.swift
  Growthook/Growthook/Presentation/Common/TabBar/TabBarController.swift
  Growthook/Growthook/Presentation/Common/UIComponents/CustomNavigationBar.swift
  Growthook/Growthook/Presentation/Common/UIComponents/RemoveInsightAlertView.swift
  Growthook/Growthook/Presentation/Common/UIComponents/UnLockCaveAlertView.swift
  Growthook/Growthook/Presentation/Common/UIComponents/UnLockInsightAlertView.swift
  Growthook/Growthook/Presentation/Home/Cell/CaveListHalfModalCell.swift
  Growthook/Growthook/Presentation/Home/Cell/InsightListCollectionViewCell.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/CaveListHalfModal.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
  Growthook/Growthook/Presentation/Home/Views/InsightListView.swift
  Growthook/Growthook/Presentation/Home/Views/NotificationAlertView.swift
Labels: 🐸 정, 🌱 Feat

#31 [Fix] #30 - ImageLiterals를 수정합니다.
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Growthook/Growthook/Global/Literals/ImageLiterals.swift
Labels: 🎈 Fix

#32 [Feature] #28 - 인사이트 작성 화면을 구현했습니다.
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Growthook/Growthook/Application/SceneDelegate.swift
  Growthook/Growthook/Global/Extension/Reactive+UIControl.swift
  Growthook/Growthook/Global/Extension/Reactive+UITextField.swift
  Growthook/Growthook/Global/Literals/ImageLiterals.swift
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Insight/InsightSelectedCaveDot.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Insight/InsightSelectedCaveDot.imageset/InsightSelectedCaveDot.svg
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Insight/insightPeroidWarning.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Insight/insightPeroidWarning.imageset/insightPeroidWarning.svg
  Growthook/Growthook/Presentation/Common/UIComponents/UITextFieldWithTintedWhenEdited.swift
  Growthook/Growthook/Presentation/Common/UIComponents/UITextViewWithTintedWhenEdited.swift
  Growthook/Growthook/Presentation/Insights/Controllers/CreatingNewInsightsViewController.swift
  Growthook/Growthook/Presentation/Insights/Controllers/InsightSelectCaveSheetViewController.swift
  Growthook/Growthook/Presentation/Insights/Controllers/InsightSelectPeriodSheetViewController.swift
  Growthook/Growthook/Presentation/Insights/NewUITextComponent/CommonCustomNavigationBar.swift
  Growthook/Growthook/Presentation/Insights/NewUITextComponent/CommonTextFieldWithBorder.swift
  Growthook/Growthook/Presentation/Insights/NewUITextComponent/CommonTextViewWithBorder.swift
  Growthook/Growthook/Presentation/Insights/NewUITextComponent/EnlargedAreaButton.swift
  Growthook/Growthook/Presentation/Insights/ViewModels/InsightsViewModel.swift
  Growthook/Growthook/Presentation/Insights/Views/Components/InsightSelectCaveTableViewCell.swift
  Growthook/Growthook/Presentation/Insights/Views/CreatingNewInsightsView.swift
  Growthook/Growthook/Presentation/Insights/Views/SelectBlockWithTitle.swift
  Growthook/Growthook/Presentation/Insights/Views/TextFieldBlockWithTitle.swift
  Growthook/Growthook/Presentation/Insights/Views/TextViewBlockWithTitle.swift
Labels: 🌱 Feat, 🦊 규보, 🎫 Comment

#37 [Feat] #28 - TextField 에 Border 색을 입히는걸 깜빡했습니다. 수정했습니다.
  Growthook/Growthook/Presentation/Insights/Controllers/CreatingNewInsightsViewController.swift
Labels: 🌱 Feat, 🦊 규보, 🎈 Fix

#33 [Feature] # 19 - 액션리스트 내의 기능을 구현합니다
  Growthook/Growthook.xcodeproj/xcshareddata/xcschemes/Growthook.xcscheme
  Growthook/Growthook/Application/SceneDelegate.swift
  Growthook/Growthook/Global/Literals/StringLiterals.swift
  Growthook/Growthook/Presentation/ActionList/Cell/ActionListCompleteTableViewCell.swift
  Growthook/Growthook/Presentation/ActionList/Cell/ActionListTableViewCell.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListBottomSheetViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListReviewViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/AlertViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/CompleteViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/InprogressViewController.swift
  Growthook/Growthook/Presentation/ActionList/ViewModels/ActionListViewModel.swift
  Growthook/Growthook/Presentation/ActionList/Views/ActionListSegmentedView.swift
  Growthook/Growthook/Presentation/CreateCave/View/EmptySeedView.swift
Labels: 🌱 Feat, 🐰 성우

#35 [Feat] #34 - 스크랩 기능 및 toast 추가
  .gitignore
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Growthook/Growthook/Application/SceneDelegate.swift
  Growthook/Growthook/Global/Extension/UICollectionView+.swift
  Growthook/Growthook/Global/Extension/UIView+.swift
  Growthook/Growthook/Global/Literals/ImageLiterals.swift
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Component/ic_scrapToast.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Component/ic_scrapToast.imageset/Frame 12.svg
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
  Growthook/Growthook/Presentation/Home/Cell/InsightListCollectionViewCell.swift
  Growthook/Growthook/Presentation/Home/Models/InsightList.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/CaveListHalfModal.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/RemoveInsightAlertViewController.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
  Growthook/Growthook/Presentation/Home/Views/InsightListView.swift
Labels: 🐸 정, 🌱 Feat

#38 [Feat] #36 - 메인, 보관함 상세 empty 뷰 구현
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/mugwort_empty_img.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/mugwort_empty_img.imageset/Group 986712.svg
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/mugwort_empty_img.imageset/Rectangle 74058.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/mugwort_empty_img.imageset/Rectangle 74058@2x.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Storage/mugwort_empty_img.imageset/Rectangle 74058@3x.png
  Growthook/Growthook/Presentation/CaveDetail/Views/CaveDetailView.swift
  Growthook/Growthook/Presentation/CreateCave/View/EmptySeedView.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
  Growthook/Growthook/Presentation/Home/Views/HomeCaveView.swift
Labels: 🐸 정, 🌱 Feat

#39 [Feature] #29 - 액션플랜 생성 뷰 하단 텍스트뷰 부분을 구현하였습니다.
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Global/Extension/UIView+.swift
  Growthook/Growthook/Global/Extension/UIViewController+.swift
  Growthook/Growthook/Global/Literals/ImageLiterals.swift
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/ActionPlan/plus_btn.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/ActionPlan/plus_btn.imageset/plus.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/ActionPlan/plus_btn.imageset/plus@2x.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/ActionPlan/plus_btn.imageset/plus@3x.png
  Growthook/Growthook/Presentation/Common/UIComponents/UITextViewWithTintedWhenEdited.swift
  Growthook/Growthook/Presentation/CreateAction/Cell/SpecificPlanCollectionViewCell.swift
  Growthook/Growthook/Presentation/CreateAction/View/CreateActionView.swift
  Growthook/Growthook/Presentation/CreateAction/View/CreateSpecificPlanView .swift
  Growthook/Growthook/Presentation/CreateAction/View/InsightView.swift
  Growthook/Growthook/Presentation/CreateAction/ViewController/CreateActionViewControlller.swift
  Growthook/Growthook/Presentation/CreateAction/ViewModel/CreateActionViewModel.swift
  Growthook/Growthook/Presentation/CreateCave/View/EmptySeedView.swift
  Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
Labels: 🌱 Feat, 😼 민주

#43 [Setting] #42 - 서버 초기세팅
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Global/Extension/Encodable+.swift
  Growthook/Growthook/Info.plist
  Growthook/Growthook/Network/Base/URLConstant.swift
Labels: ⚙️ Setting, 🐸 정
