Repository Team-Growthook/Growthook-iOS, pull requests merged in 2024-01, with the labels that each got.

#47 [Feat] #45 - Rx+Moya 를 활용한 베이스 코드를 구현합니다.
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Global/Extension/Observable+.swift
  Growthook/Growthook/Network/API/API.swift
  Growthook/Growthook/Network/Base/BaseTargetType.swift
  Growthook/Growthook/Network/Base/Networkable.swift
  Growthook/Growthook/Network/Base/URLConstant.swift
  Growthook/Growthook/Network/ServiceError/ServiceError.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: 🌱 Feat, 🦊 규보, 🎫 Comment

#52 [Feat] #49 - (⭐️중요 State 사용) 인사이트 작성 및 마이페이지 API 를 추가했습니다.
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Data/Insights/InsightsDTO.swift
  Growthook/Growthook/Data/Insights/InsightsModel.swift
  Growthook/Growthook/Data/MyPage/MyPageDTO.swift
  Growthook/Growthook/Data/MyPage/MyPageModel.swift
  Growthook/Growthook/Global/Literals/StringLiterals.swift
  Growthook/Growthook/Global/Managers/NetworkManager.swift
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/UserImage/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/UserImage/DefaultUserImage.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/UserImage/DefaultUserImage.imageset/DefaultUserImage.png
  Growthook/Growthook/Network/API/Insights/InsightsService.swift
  Growthook/Growthook/Network/API/MyPage/MyPageService.swift
  Growthook/Growthook/Network/Base/URLConstant.swift
  Growthook/Growthook/Presentation/Insights/Controllers/CreatingNewInsightsViewController.swift
  Growthook/Growthook/Presentation/Insights/Controllers/InsightSelectCaveSheetViewController.swift
  Growthook/Growthook/Presentation/Insights/NewUITextComponent/CommonCustomNavigationBar.swift
  Growthook/Growthook/Presentation/Insights/ViewModels/InsightsViewModel.swift
  Growthook/Growthook/Presentation/Insights/Views/CreatingNewInsightsView.swift
  Growthook/Growthook/Presentation/Insights/Views/FullCoverLoadingView.swift
  Growthook/Growthook/Presentation/Mypage/Controllers/MyPageUserInformationViewController.swift
  Growthook/Growthook/Presentation/Mypage/Controllers/MypageViewController.swift
  Growthook/Growthook/Presentation/Mypage/ViewModels/MyPageViewModel.swift
  Growthook/Growthook/Presentation/Mypage/Views/MyPageUserInfoBlockView.swift
Labels: 🌱 Feat, 🦊 규보

#53 [Feat] #51 - 홈 및 보관함 상세 뷰 서버 통신 구현
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Data/Cave/CaveDetailResponseDto.swift
  Growthook/Growthook/Data/Cave/CaveListResponseDto.swift
  Growthook/Growthook/Data/Cave/CavePatchRequestDto.swift
  Growthook/Growthook/Data/DTO.swift
  Growthook/Growthook/Data/Insight/PatchSeedRequestDto.swift
  Growthook/Growthook/Data/Insight/SeedAlarmResponseDto.swift
  Growthook/Growthook/Data/Insight/SeedListResponseDto.swift
  Growthook/Growthook/Data/Insight/SeedMoveRequestDto.swift
  Growthook/Growthook/Data/Insight/SeedMoveResponsetDto.swift
  Growthook/Growthook/Data/Ssuk/SsukResponseDto.swift
  Growthook/Growthook/Global/Extension/UILabel+.swift
  Growthook/Growthook/Global/Literals/StringLiterals.swift
  Growthook/Growthook/Network/API/API.swift
  Growthook/Growthook/Network/API/CaveAPI/CaveAPI.swift
  Growthook/Growthook/Network/API/SeedListAPI/SeedListAPI.swift
  Growthook/Growthook/Network/API/SsukAPI/SsukAPI.swift
  Growthook/Growthook/Network/APIService/Cave/CaveTarget.swift
  Growthook/Growthook/Network/APIService/Home/SeedListTarget.swift
  Growthook/Growthook/Network/APIService/Ssuk/SsukTarget.swift
  Growthook/Growthook/Network/Base/APIConstant.swift
  Growthook/Growthook/Network/Base/GeneralResponse.swift
  Growthook/Growthook/Network/Base/URLConstant.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailMenuBottomSheet.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/RemoveCaveAlertViewController.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewModels/CaveDetailViewModel.swift
  Growthook/Growthook/Presentation/CaveDetail/Views/CaveDescriptionView.swift
  Growthook/Growthook/Presentation/CaveDetail/Views/CaveDetailView.swift
  Growthook/Growthook/Presentation/Common/UIComponents/UnLockInsightAlertView.swift
  Growthook/Growthook/Presentation/CreateAction/Cell/SpecificPlanCollectionViewCell.swift
  Growthook/Growthook/Presentation/CreateCave/View/EmptySeedView.swift
  Growthook/Growthook/Presentation/Home/Cell/CaveCollectionViewCell.swift
  Growthook/Growthook/Presentation/Home/Cell/CaveListHalfModalCell.swift
  Growthook/Growthook/Presentation/Home/Cell/InsightListCollectionViewCell.swift
  Growthook/Growthook/Presentation/Home/Models/InsightList.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/CaveListHalfModal.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/InsightTapBottomSheet.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/RemoveInsightAlertViewController.swift
  Growthook/Growthook/Presentation/Home/ViewModels/CaveListViewModel.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
  Growthook/Growthook/Presentation/Home/ViewModels/InsightTapViewModel.swift
  Growthook/Growthook/Presentation/Home/ViewModels/RemoveInsightViewModel.swift
  Growthook/Growthook/Presentation/Home/Views/HomeCaveView.swift
  Growthook/Growthook/Presentation/Home/Views/InsightListView.swift
  Growthook/Growthook/Presentation/Home/Views/NotificationAlertView.swift
Labels: 🐸 정, 🌱 Feat, 🎈 Fix

#56 [Feat] #54 - 동굴 내용 수정 UI 구현 및 서버통신
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Global/Literals/ImageLiterals.swift
  Growthook/Growthook/Global/Literals/StringLiterals.swift
  Growthook/Growthook/Info.plist
  Growthook/Growthook/Network/API/CaveAPI/CaveAPI.swift
  Growthook/Growthook/Network/APIService/Cave/CaveTarget.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailMenuBottomSheet.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/ChangeCaveViewController.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/RemoveCaveAlertViewController.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewModels/ChangeCaveViewModel.swift
  Growthook/Growthook/Presentation/CaveDetail/Views/CaveDescriptionView.swift
  Growthook/Growthook/Presentation/CaveDetail/Views/ChangeCaveView.swift
  Growthook/Growthook/Presentation/Common/UIComponents/CustomNavigationBar.swift
  Growthook/Growthook/Presentation/Home/Cell/CaveCollectionViewCell.swift
  Growthook/Growthook/Presentation/Home/Cell/InsightListCollectionViewCell.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/CaveListHalfModal.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/InsightTapBottomSheet.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/RemoveInsightAlertViewController.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
  Growthook/Growthook/Presentation/Home/Views/Cave ListEmptyView.swift
  Growthook/Growthook/Presentation/Home/Views/HomeCaveView.swift
  Growthook/Growthook/Presentation/Home/Views/InsightListView.swift
Labels: 🐸 정, 🌱 Feat

#57 [Feature] #46 - ActionList 화면 서버 통신 구현
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook.xcodeproj/xcshareddata/xcschemes/Growthook.xcscheme
  Growthook/Growthook/Application/SceneDelegate.swift
  Growthook/Growthook/Application/SplashViewController.swift
  Growthook/Growthook/Data/ActionList/ActionListDTO.swift
  Growthook/Growthook/Global/Literals/ImageLiterals.swift
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Onboarding/btn_kakaologin.imageset/ic_kakaoLoginButton.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Onboarding/btn_kakaologin.imageset/ic_kakaoLoginButton@2x.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Onboarding/btn_kakaologin.imageset/ic_kakaoLoginButton@3x.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Onboarding/growthook_Splash.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Onboarding/growthook_Splash.imageset/growthook_Splash.svg
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Onboarding/kakao_login_large_wide.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Onboarding/kakao_login_large_wide.imageset/kakao_login_large_wide.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Onboarding/kakao_login_large_wide.imageset/kakao_login_large_wide@2x.png
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Onboarding/kakao_login_large_wide.imageset/kakao_login_large_wide@3x.png
  Growthook/Growthook/Global/Resource/Lotties/splash_growthook.json
  Growthook/Growthook/Network/API/ActionList/ActionListService.swift
  Growthook/Growthook/Network/Base/URLConstant.swift
  Growthook/Growthook/Presentation/ActionList/Cell/ActionListCompleteTableViewCell.swift
  Growthook/Growthook/Presentation/ActionList/Cell/ActionListTableViewCell.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListBottomSheetViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListReviewViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/AlertViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/CompleteViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/InprogressViewController.swift
  Growthook/Growthook/Presentation/ActionList/Model/ActionListModel.swift
  Growthook/Growthook/Presentation/ActionList/ViewModels/ActionListViewModel.swift
  Growthook/Growthook/Presentation/ActionList/Views/MainTitleBarView.swift
  Growthook/Growthook/Presentation/Common/UIComponents/UITextViewWithTintedWhenEdited.swift
  Growthook/Growthook/Presentation/Onboarding/ViewControllers/LoginViewController.swift
Labels: 🌱 Feat, 🐰 성우

#62 [Feat] #60 - 뷰 연결 작업
  Growthook/Growthook/Application/SceneDelegate.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListViewController.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
  Growthook/Growthook/Presentation/Common/TabBar/TabBarController.swift
  Growthook/Growthook/Presentation/Common/UIComponents/CustomNavigationBar.swift
  Growthook/Growthook/Presentation/CreateAction/ViewController/CreateActionViewControlller.swift
  Growthook/Growthook/Presentation/CreateCave/View/CreateCaveView.swift
  Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
  Growthook/Growthook/Presentation/CreateCave/ViewController/EmptyViewController.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
  Growthook/Growthook/Presentation/Insights/Controllers/CreatingNewInsightsViewController.swift
  Growthook/Growthook/Presentation/InsightsDetail/Controllers/InsightsDetailViewController.swift
Labels: 🐸 정, 🌱 Feat, 🦊 규보, 😼 민주, 🐰 성우

#67 [Add] #66 - 애플 로그인에 필요한 초기 세팅을 완료했습니다.
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Growthook.entitlements
Labels: 🦊 규보, 🎀 Add

#65 [Feat] #63 - 카카오로그인 구현 및 인사이트 잠금 해제 로직 수정
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Application/AppDelegate.swift
  Growthook/Growthook/Application/SceneDelegate.swift
  Growthook/Growthook/Data/Auth/LoginRequestDto.swift
  Growthook/Growthook/Data/Auth/LoginResponseDto.swift
  Growthook/Growthook/Data/Auth/RefreshTokenResponseDto.swift
  Growthook/Growthook/Data/Cave/CaveListResponseDto.swift
  Growthook/Growthook/Global/Literals/StringLiterals.swift
  Growthook/Growthook/Network/API/Auth/AuthAPI.swift
  Growthook/Growthook/Network/APIService/Auth/AuthTarget.swift
  Growthook/Growthook/Network/APIService/Cave/CaveTarget.swift
  Growthook/Growthook/Network/APIService/Home/SeedListTarget.swift
  Growthook/Growthook/Network/APIService/Ssuk/SsukTarget.swift
  Growthook/Growthook/Network/Base/APIConstant.swift
  Growthook/Growthook/Network/Base/URLConstant.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
  Growthook/Growthook/Presentation/Home/Cell/CaveCollectionViewCell.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
  Growthook/Growthook/Presentation/Home/Views/HomeCaveView.swift
  Growthook/Growthook/Presentation/Onboarding/ViewControllers/LoginViewController.swift
Labels: 🐸 정, 🌱 Feat

#68 [Fix] #61 - SeedId 수정
  Growthook/Growthook/Application/SceneDelegate.swift
  Growthook/Growthook/Presentation/CreateAction/ViewController/CreateActionViewControlller.swift
  Growthook/Growthook/Presentation/CreateAction/ViewModel/CreateActionViewModel.swift
  Growthook/Growthook/Presentation/CreateCave/ViewModel/CreateCaveViewModel.swift
  Growthook/Growthook/Presentation/InsightsDetail/Controllers/InsightsDetailViewController.swift
Labels: 🎈 Fix, 😼 민주

#70 [Fix] #69 - 홈, 동굴 상세 뷰 오류 수정
  Growthook/Growthook/Global/Literals/StringLiterals.swift
  Growthook/Growthook/Network/Base/APIConstant.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/ChangeCaveViewController.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewModels/ChangeCaveViewModel.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/InsightTapBottomSheet.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
  Growthook/Growthook/Presentation/Onboarding/ViewControllers/LoginViewController.swift
Labels: 🐸 정, 🌱 Feat, 🎈 Fix

#72 [Feature] #64 - 서버 대응 및 애플로그인을 구현합니다
  Growthook/Growthook/Application/SplashViewController.swift
  Growthook/Growthook/Data/ActionList/ActionListDTO.swift
  Growthook/Growthook/Data/Auth/LoginRequestDto.swift
  Growthook/Growthook/Global/Literals/StringLiterals.swift
  Growthook/Growthook/Presentation/ActionList/Cell/ActionListCompleteTableViewCell.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListReviewViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/CompleteViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/InprogressViewController.swift
  Growthook/Growthook/Presentation/ActionList/ViewModels/ActionListViewModel.swift
  Growthook/Growthook/Presentation/Mypage/Controllers/MypageViewController.swift
  Growthook/Growthook/Presentation/Mypage/ViewModels/MyPageViewModel.swift
  Growthook/Growthook/Presentation/Onboarding/ViewControllers/LoginViewController.swift
Labels: 🌱 Feat, 🐰 성우

#77 [Fix] #76 - 인사이트 뷰 스크랩 버튼 추가
  Growthook/Growthook/Presentation/CreateAction/View/InsightView.swift
Labels: 🦋 Design, 🌱 Feat, 🎀 Add, 🎈 Fix, 😼 민주

#78 [Feature] #71 - 소셜 로그인(APPLE) 기능 구현
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Application/KeychainHelper.swift
  Growthook/Growthook/Application/SplashViewController.swift
  Growthook/Growthook/Global/Extension/Observable+.swift
  Growthook/Growthook/Global/Literals/StringLiterals.swift
  Growthook/Growthook/Network/Base/APIConstant.swift
  Growthook/Growthook/Presentation/ActionList/ViewModels/ActionListViewModel.swift
  Growthook/Growthook/Presentation/Mypage/ViewModels/MyPageViewModel.swift
  Growthook/Growthook/Presentation/Onboarding/ViewControllers/LoginViewController.swift
Labels: 🌱 Feat, 🐰 성우

#81 [Feat] #73 - 카카오 로그인 구현
  Growthook/Growthook/Network/API/Auth/AuthAPI.swift
  Growthook/Growthook/Network/APIService/Auth/AuthTarget.swift
  Growthook/Growthook/Network/Base/URLConstant.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
  Growthook/Growthook/Presentation/Mypage/Controllers/MyPageUserInformationViewController.swift
  Growthook/Growthook/Presentation/Onboarding/ViewControllers/LoginViewController.swift
Labels: 🐸 정, 🌱 Feat

#87 [Fix] - #74 토큰 만료로 인한 재시도 오퍼레이터 추가
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Application/SplashViewController.swift
  Growthook/Growthook/Application/TokenManager.swift
  Growthook/Growthook/Global/Extension/Observable+.swift
  Growthook/Growthook/Network/API/ActionList/ActionListService.swift
  Growthook/Growthook/Network/API/Auth/AuthAPI.swift
  Growthook/Growthook/Network/API/CreateAction/CreateActionService.swift
  Growthook/Growthook/Network/API/CreateCave/CreateCaveService.swift
  Growthook/Growthook/Network/API/Insights/InsightsDetailService.swift
  Growthook/Growthook/Network/API/Insights/InsightsService.swift
  Growthook/Growthook/Network/API/MyPage/MyPageService.swift
  Growthook/Growthook/Network/APIService/Home/SeedListTarget.swift
  Growthook/Growthook/Network/ServiceError/ServiceError.swift
  Growthook/Growthook/Presentation/Onboarding/ViewControllers/LoginViewController.swift
Labels: 🌱 Feat, 🦊 규보, 🎈 Fix

#91 [Feature] #90 - 수정사항 반영 및 추가 구현
  Growthook/Growthook/Data/ActionList/ActionListDTO.swift
  Growthook/Growthook/Network/API/ActionList/ActionListService.swift
  Growthook/Growthook/Network/Base/URLConstant.swift
  Growthook/Growthook/Presentation/ActionList/Cell/ActionListCompleteTableViewCell.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/CompleteViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/InprogressViewController.swift
  Growthook/Growthook/Presentation/ActionList/ViewModels/ActionListViewModel.swift
Labels: 🌱 Feat, 🐰 성우

#89 [Fix] #86 - 기획 변동사항 반영
  Growthook/Growthook/Global/Literals/ImageLiterals.swift
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Home/profile_default.imageset/Contents.json
  Growthook/Growthook/Global/Resource/AssetCatalog/Image.xcassets/Home/profile_default.imageset/profile_default.svg
  Growthook/Growthook/Network/API/Auth/AuthAPI.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewModels/ChangeCaveViewModel.swift
  Growthook/Growthook/Presentation/CaveDetail/Views/CaveDescriptionView.swift
  Growthook/Growthook/Presentation/CreateAction/ViewController/CreateActionViewControlller.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/CaveListHalfModal.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
  Growthook/Growthook/Presentation/Mypage/Controllers/MyPageUserInformationViewController.swift
Labels: 🐸 정, 🌱 Feat

#97 [Fix] #93 - QA 반영
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Presentation/CreateAction/ViewController/CreateActionViewControlller.swift
  Growthook/Growthook/Presentation/CreateCave/View/CaveEmptyView.swift
  Growthook/Growthook/Presentation/CreateCave/View/CaveInfoView.swift
  Growthook/Growthook/Presentation/CreateCave/View/CreateCaveView.swift
  Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveEmptyViewController.swift
  Growthook/Growthook/Presentation/CreateCave/ViewController/CreateCaveViewController.swift
  Growthook/Growthook/Presentation/CreateCave/ViewModel/CreateCaveViewModel.swift
  Growthook/Growthook/Presentation/Insights/NewUITextComponent/CommonTextFieldWithBorder.swift
  Growthook/Growthook/Presentation/InsightsDetail/Controllers/InsightsDetailViewController.swift
Labels: 😼 민주

#99 [Fix] #98 - 마이페이지 탈퇴, 로그아웃 기능 추가
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Global/Extension/UILabel+.swift
  Growthook/Growthook/Global/Literals/StringLiterals.swift
  Growthook/Growthook/Presentation/Mypage/Controllers/LogoutAlertViewController.swift
  Growthook/Growthook/Presentation/Mypage/Controllers/MyPageUserInformationViewController.swift
  Growthook/Growthook/Presentation/Mypage/Controllers/MypageViewController.swift
  Growthook/Growthook/Presentation/Mypage/Views/MyPageAlertView.swift
Labels: 🎈 Fix

#96 [Fix] #94 - QA에서 인지하게 된 이슈를 대응합니다
  Growthook/Growthook/Presentation/ActionList/Cell/ActionListCompleteTableViewCell.swift
  Growthook/Growthook/Presentation/ActionList/Cell/ActionListTableViewCell.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListReviewViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/ActionListViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/AlertViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/CompleteViewController.swift
  Growthook/Growthook/Presentation/ActionList/Controllers/InprogressViewController.swift
  Growthook/Growthook/Presentation/ActionList/ViewModels/ActionListViewModel.swift
  Growthook/Growthook/Presentation/ActionList/Views/ActionListSegmentedView.swift
  Growthook/Growthook/Presentation/Onboarding/ViewControllers/LoginViewController.swift
  Growthook/Growthook/Presentation/Onboarding/ViewControllers/PageContentsViewController.swift
Labels: 🎈 Fix, 🐰 성우

#101 [Fix] #95 - QA 반영
  Growthook/Growthook.xcodeproj/project.pbxproj
  Growthook/Growthook/Application/AppDelegate.swift
  Growthook/Growthook/Info.plist
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
  Growthook/Growthook/Presentation/Home/Cell/InsightListCollectionViewCell.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
Labels: 🐸 정, 🎈 Fix

#106 [Fix] #105 - 동굴 뷰에서 인사이트 삭제 이후 반영 안되는 에러 수정
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/RemoveCaveAlertViewController.swift
Labels: 🐸 정, 🎈 Fix

#104 [Fix] - #74 버튼 UI 수정
  Growthook/Growthook/Data/MyPage/MyPageDTO.swift
  Growthook/Growthook/Presentation/InsightsDetail/Controllers/InsightsDetailViewController.swift
  Growthook/Growthook/Presentation/Mypage/Controllers/MyPageUserInformationViewController.swift
  Growthook/Growthook/Presentation/Mypage/Controllers/MypageViewController.swift
  Growthook/Growthook/Presentation/Mypage/ViewModels/MyPageViewModel.swift
Labels: 🦊 규보, 🎈 Fix

#114 [Fix] #102 - 액션플랜 생성 뷰 확인 버튼 비활성화
  Growthook/Growthook/Info.plist
  Growthook/Growthook/Presentation/CreateAction/View/CreateActionView.swift
Labels: 🎈 Fix, 😼 민주

#116 [Fix] #113 - API 수정
  Growthook/Growthook/Network/API/Auth/AuthAPI.swift
  Growthook/Growthook/Network/API/CaveAPI/CaveAPI.swift
  Growthook/Growthook/Network/API/SeedListAPI/SeedListAPI.swift
  Growthook/Growthook/Network/API/SsukAPI/SsukAPI.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewModels/ChangeCaveViewModel.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
Labels: 🐸 정, 🎈 Fix

#117 [Fix] - #74 Refresh Token 만료 이슈 해결
  Growthook/Growthook/Application/TokenManager.swift
Labels: 🦊 규보, 🎈 Fix

#119 [Fix] #115 - 스플래시 뷰 로직 수정
  Growthook/Growthook/Application/SplashViewController.swift
Labels: 🎈 Fix, 😼 민주

#122 Fix/#121 - 스크랩 에러 해결
  Growthook/Growthook/Network/API/Auth/AuthAPI.swift
  Growthook/Growthook/Presentation/CaveDetail/ViewControllers/CaveDetailViewController.swift
  Growthook/Growthook/Presentation/Home/ViewControllers/HomeViewController.swift
  Growthook/Growthook/Presentation/Home/ViewModels/HomeViewModel.swift
Labels: 🎈 Fix, 😼 민주

#120 UI Fix
  Growthook/Growthook/Presentation/InsightsDetail/Views/InsightsDetailMemoView.swift
Labels: 🦊 규보, 🎈 Fix
